In [1]:
import pandas as pd
import io
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from scipy import stats
import numpy as np

In [2]:
df=pd.read_csv("Churn_Modelling.csv")

In [3]:
df.head()
df.tail()
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [4]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
X = df.iloc[:,:-1].values
X

array([[1, 15634602, 'Hargrave', ..., 1, 1, 101348.88],
       [2, 15647311, 'Hill', ..., 0, 1, 112542.58],
       [3, 15619304, 'Onio', ..., 1, 0, 113931.57],
       ...,
       [9998, 15584532, 'Liu', ..., 0, 1, 42085.58],
       [9999, 15682355, 'Sabbatini', ..., 1, 0, 92888.52],
       [10000, 15628319, 'Walker', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
Y = df.iloc[:,-1].values
Y

array([1, 0, 1, ..., 1, 1, 0])

In [7]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [8]:
data = df.drop(['Surname', 'Geography','Gender'], axis=1)

In [9]:
data.head()

RowNumber  CustomerId  CreditScore  Age  Tenure    Balance  NumOfProducts  \
0          1    15634602          619   42       2       0.00              1   
1          2    15647311          608   41       1   83807.86              1   
2          3    15619304          502   42       8  159660.80              3   
3          4    15701354          699   39       1       0.00              2   
4          5    15737888          850   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [10]:
scaler=MinMaxScaler()
df1=pd.DataFrame(scaler.fit_transform(data))
print(df1)

          0         1      2         3    4         5         6    7    8   \
0     0.0000  0.275616  0.538  0.324324  0.2  0.000000  0.000000  1.0  1.0   
1     0.0001  0.326454  0.516  0.310811  0.1  0.334031  0.000000  0.0  1.0   
2     0.0002  0.214421  0.304  0.324324  0.8  0.636357  0.666667  1.0  0.0   
3     0.0003  0.542636  0.698  0.283784  0.1  0.000000  0.333333  0.0  0.0   
4     0.0004  0.688778  1.000  0.337838  0.2  0.500246  0.000000  1.0  1.0   
...      ...       ...    ...       ...  ...       ...       ...  ...  ...   
9995  0.9996  0.162119  0.842  0.283784  0.5  0.000000  0.333333  1.0  0.0   
9996  0.9997  0.016765  0.332  0.229730  1.0  0.228657  0.000000  1.0  1.0   
9997  0.9998  0.075327  0.718  0.243243  0.7  0.000000  0.000000  0.0  1.0   
9998  0.9999  0.466637  0.844  0.324324  0.3  0.299226  0.333333  1.0  0.0   
9999  1.0000  0.250483  0.884  0.135135  0.4  0.518708  0.000000  1.0  0.0   

            9    10  
0     0.506735  1.0  
1     0.562709  0.0

In [11]:
X=df.iloc[:,:-1].values
Y=df.iloc[:,-1].values
print(X)
print(Y)

[[1 15634602 'Hargrave' ... 1 1 101348.88]
 [2 15647311 'Hill' ... 0 1 112542.58]
 [3 15619304 'Onio' ... 1 0 113931.57]
 ...
 [9998 15584532 'Liu' ... 0 1 42085.58]
 [9999 15682355 'Sabbatini' ... 1 0 92888.52]
 [10000 15628319 'Walker' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [12]:
X_train ,X_test ,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)
print("X_train\n")
print(X_train)
print("\nLenght of X_train ",len(X_train))
print("\nX_test\n")
print(X_test)
print("\nLenght of X_test ",len(X_test))

X_train

[[8506 15791535 'Caraway' ... 0 0 39608.58]
 [7506 15660528 'Niu' ... 1 0 99341.87]
 [4907 15571244 'Tung' ... 0 1 141426.78]
 ...
 [5815 15725882 'Feng' ... 1 1 54495.82]
 [6243 15673333 'Wilson' ... 1 1 153373.71]
 [7642 15667460 'Moore' ... 1 1 24748.89]]

Lenght of X_train  8000

X_test

[[9931 15713604 'Rossi' ... 0 1 172646.88]
 [9735 15583221 'Arnold' ... 1 1 20881.96]
 [6212 15793116 'Beneventi' ... 0 0 196278.32]
 ...
 [374 15688074 'Gregory' ... 1 1 187658.09]
 [389 15748936 'Whitehead' ... 0 1 162922.65]
 [6435 15703167 'Rouse' ... 1 0 193903.06]]

Lenght of X_test  2000
